name: Build & Deploy (Next.js → Azure Web App)

on:
  push:
    branches: [ main ]

env:
  APP_DIR: '.'
  AZURE_WEBAPP_NAME: 'uxtester-platform'   # 如不一致请改成你的 Web App 名

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      - name: Install deps (clean)
        working-directory: ${{ env.APP_DIR }}
        run: npm ci

      # 强制校验：没有 next 直接 fail，避免把坏包推上去
      - name: Verify Next exists
        working-directory: ${{ env.APP_DIR }}
        run: |
          npm ls next
          npx next --version

      - name: Build
        working-directory: ${{ env.APP_DIR }}
        run: npm run build

      # 先不裁剪，确保 node_modules（含 next）随包部署；站点跑起来后再考虑瘦身
      # - name: Prune to production deps
      #   working-directory: ${{ env.APP_DIR }}
      #   run: npm prune --production

      # 打包部署产物（包含 node_modules / .next / public / package.json / lock）
      - name: Create deploy artifact
        working-directory: ${{ env.APP_DIR }}
        run: |
          mkdir -p ../artifact
          rsync -a --delete \
            --include="/node_modules/***" \
            --include="/.next/***" \
            --include="/public/***" \
            --include="/package.json" \
            --include="/package-lock.json" \
            --include="/next.config.js" \
            --include="/.npmrc" \
            --exclude="*" \
            ./ ../artifact/
          cd ../artifact && zip -r ../package.zip .
      - name: Show artifact contents
        run: |
          echo "Artifact size:" && ls -lh package.zip
          unzip -l package.zip | head -n 60

      # 方式 A：OIDC 登录（如已配置下列三个 Secrets）
      - name: Azure login (OIDC)
        if: ${{ secrets.AZURE_CLIENT_ID && secrets.AZURE_TENANT_ID && secrets.AZURE_SUBSCRIPTION_ID }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy with OIDC
        if: ${{ success() && secrets.AZURE_CLIENT_ID && secrets.AZURE_TENANT_ID && secrets.AZURE_SUBSCRIPTION_ID }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: package.zip

      # 方式 B：发布配置（如未配置 OIDC，则使用 AZURE_WEBAPP_PUBLISH_PROFILE）
      - name: Deploy with Publish Profile
        if: ${{ !(secrets.AZURE_CLIENT_ID && secrets.AZURE_TENANT_ID && secrets.AZURE_SUBSCRIPTION_ID) && secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: package.zip

      - name: Fail if not deployed
        if: ${{ ! ( (secrets.AZURE_CLIENT_ID && secrets.AZURE_TENANT_ID && secrets.AZURE_SUBSCRIPTION_ID) || secrets.AZURE_WEBAPP_PUBLISH_PROFILE ) }}
        run: |
          echo "❌ Neither OIDC secrets nor publish profile secret is set."
          exit 1