name: Build & Deploy (Next.js → Azure Web App)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 安装依赖（根据 package-lock 一致性）
      - name: Install deps
        run: |
          pwd && ls -la
          npm ci

      # 自检：必须能找到 next
      - name: Check next version
        run: |
          pwd && ls -la
          npx next --version

      # 构建 Next.js
      - name: Build
        run: |
          pwd && ls -la
          npm run build

      # 校验 next 依赖存在
      - name: Verify next dependency
        run: |
          pwd && ls -la
          npm ls next

      # 校验 next 可执行文件
      - name: Verify next executable
        run: |
          pwd && ls -la
          test -x node_modules/.bin/next && node_modules/.bin/next --version

      # 精简到生产依赖（next 在 dependencies 中会被保留）
      # - name: Prune to production deps
      #   run: npm prune --production

      # 登录 Azure（OIDC）
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 部署到 Web App（把当前目录作为包发布）
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'uxtester-platform'   # ← 如果你的 App Service 名不同，请同步修改
          package: '.'
